#include <dartpy/pointers.h>
#include <dart/dart.h>


#include <boost/python.hpp>
#include <cmath>

/* postinclude */

void _ZN4dart8dynamics19ReferentialSkeletonE()
{
::boost::python::object parent_object(::boost::python::scope().attr("dynamics"));
::boost::python::scope parent_scope(parent_object);

::boost::python::class_<dart::dynamics::ReferentialSkeleton, ::boost::noncopyable, ::boost::python::bases<dart::dynamics::MetaSkeleton > >("ReferentialSkeleton", boost::python::no_init)
.def("setName", static_cast<const std::string &(dart::dynamics::ReferentialSkeleton::*)(const std::string &)>(&dart::dynamics::ReferentialSkeleton::setName), ::boost::python::return_value_policy<boost::python::copy_const_reference >(), (::boost::python::arg("_name")))
.def("getName", static_cast<const std::string &(dart::dynamics::ReferentialSkeleton::*)() const>(&dart::dynamics::ReferentialSkeleton::getName), ::boost::python::return_value_policy<boost::python::copy_const_reference >())
.def("getNumBodyNodes", static_cast<std::size_t (dart::dynamics::ReferentialSkeleton::*)() const>(&dart::dynamics::ReferentialSkeleton::getNumBodyNodes))
.def("getBodyNode", static_cast<dart::dynamics::BodyNode *(dart::dynamics::ReferentialSkeleton::*)(std::size_t)>(&dart::dynamics::ReferentialSkeleton::getBodyNode), ::boost::python::return_value_policy<boost::python::return_by_smart_ptr<dart::dynamics::BodyNodePtr> >(), (::boost::python::arg("_idx")))
.def("getBodyNodes", static_cast<const std::vector<dart::dynamics::BodyNode *> &(dart::dynamics::ReferentialSkeleton::*)()>(&dart::dynamics::ReferentialSkeleton::getBodyNodes), ::boost::python::return_value_policy<boost::python::copy_const_reference >())
.def("getIndexOf", static_cast<std::size_t (dart::dynamics::ReferentialSkeleton::*)(const dart::dynamics::BodyNode *, bool) const>(&dart::dynamics::ReferentialSkeleton::getIndexOf), (::boost::python::arg("_bn"), ::boost::python::arg("_warning") = true))
.def("getNumJoints", static_cast<std::size_t (dart::dynamics::ReferentialSkeleton::*)() const>(&dart::dynamics::ReferentialSkeleton::getNumJoints))
.def("getJoint", static_cast<dart::dynamics::Joint *(dart::dynamics::ReferentialSkeleton::*)(std::size_t)>(&dart::dynamics::ReferentialSkeleton::getJoint), ::boost::python::return_value_policy<boost::python::return_by_smart_ptr<dart::dynamics::JointPtr> >(), (::boost::python::arg("_idx")))
.def("getIndexOf", static_cast<std::size_t (dart::dynamics::ReferentialSkeleton::*)(const dart::dynamics::Joint *, bool) const>(&dart::dynamics::ReferentialSkeleton::getIndexOf), (::boost::python::arg("_joint"), ::boost::python::arg("_warning") = true))
.def("getNumDofs", static_cast<std::size_t (dart::dynamics::ReferentialSkeleton::*)() const>(&dart::dynamics::ReferentialSkeleton::getNumDofs))
.def("getDof", static_cast<dart::dynamics::DegreeOfFreedom *(dart::dynamics::ReferentialSkeleton::*)(std::size_t)>(&dart::dynamics::ReferentialSkeleton::getDof), ::boost::python::return_value_policy<boost::python::return_by_smart_ptr<dart::dynamics::DegreeOfFreedomPtr> >(), (::boost::python::arg("_idx")))
.def("getDofs", static_cast<const std::vector<dart::dynamics::DegreeOfFreedom *> &(dart::dynamics::ReferentialSkeleton::*)()>(&dart::dynamics::ReferentialSkeleton::getDofs), ::boost::python::return_value_policy<boost::python::copy_const_reference >())
.def("getIndexOf", static_cast<std::size_t (dart::dynamics::ReferentialSkeleton::*)(const dart::dynamics::DegreeOfFreedom *, bool) const>(&dart::dynamics::ReferentialSkeleton::getIndexOf), (::boost::python::arg("_dof"), ::boost::python::arg("_warning") = true))
.def("getJacobian", static_cast<dart::math::Jacobian (dart::dynamics::ReferentialSkeleton::*)(const dart::dynamics::JacobianNode *) const>(&dart::dynamics::ReferentialSkeleton::getJacobian), (::boost::python::arg("_node")))
.def("getJacobian", static_cast<dart::math::Jacobian (dart::dynamics::ReferentialSkeleton::*)(const dart::dynamics::JacobianNode *, const dart::dynamics::Frame *) const>(&dart::dynamics::ReferentialSkeleton::getJacobian), (::boost::python::arg("_node"), ::boost::python::arg("_inCoordinatesOf")))
.def("getJacobian", static_cast<dart::math::Jacobian (dart::dynamics::ReferentialSkeleton::*)(const dart::dynamics::JacobianNode *, const Eigen::Vector3d &) const>(&dart::dynamics::ReferentialSkeleton::getJacobian), (::boost::python::arg("_node"), ::boost::python::arg("_localOffset")))
.def("getJacobian", static_cast<dart::math::Jacobian (dart::dynamics::ReferentialSkeleton::*)(const dart::dynamics::JacobianNode *, const Eigen::Vector3d &, const dart::dynamics::Frame *) const>(&dart::dynamics::ReferentialSkeleton::getJacobian), (::boost::python::arg("_node"), ::boost::python::arg("_localOffset"), ::boost::python::arg("_inCoordinatesOf")))
.def("getWorldJacobian", static_cast<dart::math::Jacobian (dart::dynamics::ReferentialSkeleton::*)(const dart::dynamics::JacobianNode *) const>(&dart::dynamics::ReferentialSkeleton::getWorldJacobian), (::boost::python::arg("_node")))
.def("getWorldJacobian", static_cast<dart::math::Jacobian (dart::dynamics::ReferentialSkeleton::*)(const dart::dynamics::JacobianNode *, const Eigen::Vector3d &) const>(&dart::dynamics::ReferentialSkeleton::getWorldJacobian), (::boost::python::arg("_node"), ::boost::python::arg("_localOffset")))
.def("getLinearJacobian", static_cast<dart::math::LinearJacobian (dart::dynamics::ReferentialSkeleton::*)(const dart::dynamics::JacobianNode *, const dart::dynamics::Frame *) const>(&dart::dynamics::ReferentialSkeleton::getLinearJacobian), (::boost::python::arg("_node"), ::boost::python::arg("_inCoordinatesOf")))
.def("getLinearJacobian", static_cast<dart::math::LinearJacobian (dart::dynamics::ReferentialSkeleton::*)(const dart::dynamics::JacobianNode *, const Eigen::Vector3d &, const dart::dynamics::Frame *) const>(&dart::dynamics::ReferentialSkeleton::getLinearJacobian), (::boost::python::arg("_node"), ::boost::python::arg("_localOffset"), ::boost::python::arg("_inCoordinatesOf")))
.def("getAngularJacobian", static_cast<dart::math::AngularJacobian (dart::dynamics::ReferentialSkeleton::*)(const dart::dynamics::JacobianNode *, const dart::dynamics::Frame *) const>(&dart::dynamics::ReferentialSkeleton::getAngularJacobian), (::boost::python::arg("_node"), ::boost::python::arg("_inCoordinatesOf")))
.def("getJacobianSpatialDeriv", static_cast<dart::math::Jacobian (dart::dynamics::ReferentialSkeleton::*)(const dart::dynamics::JacobianNode *) const>(&dart::dynamics::ReferentialSkeleton::getJacobianSpatialDeriv), (::boost::python::arg("_node")))
.def("getJacobianSpatialDeriv", static_cast<dart::math::Jacobian (dart::dynamics::ReferentialSkeleton::*)(const dart::dynamics::JacobianNode *, const dart::dynamics::Frame *) const>(&dart::dynamics::ReferentialSkeleton::getJacobianSpatialDeriv), (::boost::python::arg("_node"), ::boost::python::arg("_inCoordinatesOf")))
.def("getJacobianSpatialDeriv", static_cast<dart::math::Jacobian (dart::dynamics::ReferentialSkeleton::*)(const dart::dynamics::JacobianNode *, const Eigen::Vector3d &) const>(&dart::dynamics::ReferentialSkeleton::getJacobianSpatialDeriv), (::boost::python::arg("_node"), ::boost::python::arg("_localOffset")))
.def("getJacobianSpatialDeriv", static_cast<dart::math::Jacobian (dart::dynamics::ReferentialSkeleton::*)(const dart::dynamics::JacobianNode *, const Eigen::Vector3d &, const dart::dynamics::Frame *) const>(&dart::dynamics::ReferentialSkeleton::getJacobianSpatialDeriv), (::boost::python::arg("_node"), ::boost::python::arg("_localOffset"), ::boost::python::arg("_inCoordinatesOf")))
.def("getJacobianClassicDeriv", static_cast<dart::math::Jacobian (dart::dynamics::ReferentialSkeleton::*)(const dart::dynamics::JacobianNode *) const>(&dart::dynamics::ReferentialSkeleton::getJacobianClassicDeriv), (::boost::python::arg("_node")))
.def("getJacobianClassicDeriv", static_cast<dart::math::Jacobian (dart::dynamics::ReferentialSkeleton::*)(const dart::dynamics::JacobianNode *, const dart::dynamics::Frame *) const>(&dart::dynamics::ReferentialSkeleton::getJacobianClassicDeriv), (::boost::python::arg("_node"), ::boost::python::arg("_inCoordinatesOf")))
.def("getJacobianClassicDeriv", static_cast<dart::math::Jacobian (dart::dynamics::ReferentialSkeleton::*)(const dart::dynamics::JacobianNode *, const Eigen::Vector3d &, const dart::dynamics::Frame *) const>(&dart::dynamics::ReferentialSkeleton::getJacobianClassicDeriv), (::boost::python::arg("_node"), ::boost::python::arg("_localOffset"), ::boost::python::arg("_inCoordinatesOf")))
.def("getLinearJacobianDeriv", static_cast<dart::math::LinearJacobian (dart::dynamics::ReferentialSkeleton::*)(const dart::dynamics::JacobianNode *, const dart::dynamics::Frame *) const>(&dart::dynamics::ReferentialSkeleton::getLinearJacobianDeriv), (::boost::python::arg("_node"), ::boost::python::arg("_inCoordinatesOf")))
.def("getLinearJacobianDeriv", static_cast<dart::math::LinearJacobian (dart::dynamics::ReferentialSkeleton::*)(const dart::dynamics::JacobianNode *, const Eigen::Vector3d &, const dart::dynamics::Frame *) const>(&dart::dynamics::ReferentialSkeleton::getLinearJacobianDeriv), (::boost::python::arg("_node"), ::boost::python::arg("_localOffset"), ::boost::python::arg("_inCoordinatesOf")))
.def("getAngularJacobianDeriv", static_cast<dart::math::AngularJacobian (dart::dynamics::ReferentialSkeleton::*)(const dart::dynamics::JacobianNode *, const dart::dynamics::Frame *) const>(&dart::dynamics::ReferentialSkeleton::getAngularJacobianDeriv), (::boost::python::arg("_node"), ::boost::python::arg("_inCoordinatesOf")))
.def("getMass", static_cast<double (dart::dynamics::ReferentialSkeleton::*)() const>(&dart::dynamics::ReferentialSkeleton::getMass))
.def("getMassMatrix", static_cast<const Eigen::MatrixXd &(dart::dynamics::ReferentialSkeleton::*)() const>(&dart::dynamics::ReferentialSkeleton::getMassMatrix), ::boost::python::return_value_policy<boost::python::copy_const_reference >())
.def("getAugMassMatrix", static_cast<const Eigen::MatrixXd &(dart::dynamics::ReferentialSkeleton::*)() const>(&dart::dynamics::ReferentialSkeleton::getAugMassMatrix), ::boost::python::return_value_policy<boost::python::copy_const_reference >())
.def("getInvMassMatrix", static_cast<const Eigen::MatrixXd &(dart::dynamics::ReferentialSkeleton::*)() const>(&dart::dynamics::ReferentialSkeleton::getInvMassMatrix), ::boost::python::return_value_policy<boost::python::copy_const_reference >())
.def("getInvAugMassMatrix", static_cast<const Eigen::MatrixXd &(dart::dynamics::ReferentialSkeleton::*)() const>(&dart::dynamics::ReferentialSkeleton::getInvAugMassMatrix), ::boost::python::return_value_policy<boost::python::copy_const_reference >())
.def("getCoriolisForces", static_cast<const Eigen::VectorXd &(dart::dynamics::ReferentialSkeleton::*)() const>(&dart::dynamics::ReferentialSkeleton::getCoriolisForces), ::boost::python::return_value_policy<boost::python::copy_const_reference >())
.def("getGravityForces", static_cast<const Eigen::VectorXd &(dart::dynamics::ReferentialSkeleton::*)() const>(&dart::dynamics::ReferentialSkeleton::getGravityForces), ::boost::python::return_value_policy<boost::python::copy_const_reference >())
.def("getCoriolisAndGravityForces", static_cast<const Eigen::VectorXd &(dart::dynamics::ReferentialSkeleton::*)() const>(&dart::dynamics::ReferentialSkeleton::getCoriolisAndGravityForces), ::boost::python::return_value_policy<boost::python::copy_const_reference >())
.def("getExternalForces", static_cast<const Eigen::VectorXd &(dart::dynamics::ReferentialSkeleton::*)() const>(&dart::dynamics::ReferentialSkeleton::getExternalForces), ::boost::python::return_value_policy<boost::python::copy_const_reference >())
.def("getConstraintForces", static_cast<const Eigen::VectorXd &(dart::dynamics::ReferentialSkeleton::*)() const>(&dart::dynamics::ReferentialSkeleton::getConstraintForces), ::boost::python::return_value_policy<boost::python::copy_const_reference >())
.def("clearExternalForces", static_cast<void (dart::dynamics::ReferentialSkeleton::*)()>(&dart::dynamics::ReferentialSkeleton::clearExternalForces))
.def("clearInternalForces", static_cast<void (dart::dynamics::ReferentialSkeleton::*)()>(&dart::dynamics::ReferentialSkeleton::clearInternalForces))
.def("getKineticEnergy", static_cast<double (dart::dynamics::ReferentialSkeleton::*)() const>(&dart::dynamics::ReferentialSkeleton::getKineticEnergy))
.def("getPotentialEnergy", static_cast<double (dart::dynamics::ReferentialSkeleton::*)() const>(&dart::dynamics::ReferentialSkeleton::getPotentialEnergy))
.def("getCOM", static_cast<Eigen::Vector3d (dart::dynamics::ReferentialSkeleton::*)(const dart::dynamics::Frame *) const>(&dart::dynamics::ReferentialSkeleton::getCOM), (::boost::python::arg("_withRespectTo")))
.def("getCOMSpatialVelocity", static_cast<Eigen::Vector6d (dart::dynamics::ReferentialSkeleton::*)(const dart::dynamics::Frame *, const dart::dynamics::Frame *) const>(&dart::dynamics::ReferentialSkeleton::getCOMSpatialVelocity), (::boost::python::arg("_relativeTo"), ::boost::python::arg("_inCoordinatesOf")))
.def("getCOMLinearVelocity", static_cast<Eigen::Vector3d (dart::dynamics::ReferentialSkeleton::*)(const dart::dynamics::Frame *, const dart::dynamics::Frame *) const>(&dart::dynamics::ReferentialSkeleton::getCOMLinearVelocity), (::boost::python::arg("_relativeTo"), ::boost::python::arg("_inCoordinatesOf")))
.def("getCOMSpatialAcceleration", static_cast<Eigen::Vector6d (dart::dynamics::ReferentialSkeleton::*)(const dart::dynamics::Frame *, const dart::dynamics::Frame *) const>(&dart::dynamics::ReferentialSkeleton::getCOMSpatialAcceleration), (::boost::python::arg("_relativeTo"), ::boost::python::arg("_inCoordinatesOf")))
.def("getCOMLinearAcceleration", static_cast<Eigen::Vector3d (dart::dynamics::ReferentialSkeleton::*)(const dart::dynamics::Frame *, const dart::dynamics::Frame *) const>(&dart::dynamics::ReferentialSkeleton::getCOMLinearAcceleration), (::boost::python::arg("_relativeTo"), ::boost::python::arg("_inCoordinatesOf")))
.def("getCOMJacobian", static_cast<dart::math::Jacobian (dart::dynamics::ReferentialSkeleton::*)(const dart::dynamics::Frame *) const>(&dart::dynamics::ReferentialSkeleton::getCOMJacobian), (::boost::python::arg("_inCoordinatesOf")))
.def("getCOMLinearJacobian", static_cast<dart::math::LinearJacobian (dart::dynamics::ReferentialSkeleton::*)(const dart::dynamics::Frame *) const>(&dart::dynamics::ReferentialSkeleton::getCOMLinearJacobian), (::boost::python::arg("_inCoordinatesOf")))
.def("getCOMJacobianSpatialDeriv", static_cast<dart::math::Jacobian (dart::dynamics::ReferentialSkeleton::*)(const dart::dynamics::Frame *) const>(&dart::dynamics::ReferentialSkeleton::getCOMJacobianSpatialDeriv), (::boost::python::arg("_inCoordinatesOf")))
.def("getCOMLinearJacobianDeriv", static_cast<dart::math::LinearJacobian (dart::dynamics::ReferentialSkeleton::*)(const dart::dynamics::Frame *) const>(&dart::dynamics::ReferentialSkeleton::getCOMLinearJacobianDeriv), (::boost::python::arg("_inCoordinatesOf")))
;
}

/* footer */
