#include <dartpy/pointers.h>
#include <dart/dart.h>


#include <boost/python.hpp>
#include <cmath>

/* postinclude */

void _ZN4dart8dynamics12ZeroDofJointE()
{
::boost::python::object parent_object(::boost::python::scope().attr("dynamics"));
::boost::python::scope parent_scope(parent_object);

::boost::python::class_<dart::dynamics::ZeroDofJoint, ::boost::noncopyable, ::boost::python::bases<dart::dynamics::Joint > >("ZeroDofJoint", boost::python::no_init)
.def("getZeroDofJointProperties", static_cast<dart::dynamics::ZeroDofJoint::Properties (dart::dynamics::ZeroDofJoint::*)() const>(&dart::dynamics::ZeroDofJoint::getZeroDofJointProperties))
.def("getDof", static_cast<dart::dynamics::DegreeOfFreedom *(dart::dynamics::ZeroDofJoint::*)(std::size_t)>(&dart::dynamics::ZeroDofJoint::getDof), ::boost::python::return_value_policy<boost::python::return_by_smart_ptr<dart::dynamics::DegreeOfFreedomPtr> >(), (::boost::python::arg("")))
.def("setDofName", static_cast<const std::string &(dart::dynamics::ZeroDofJoint::*)(std::size_t, const std::string &, bool)>(&dart::dynamics::ZeroDofJoint::setDofName), ::boost::python::return_value_policy<boost::python::copy_const_reference >(), (::boost::python::arg(""), ::boost::python::arg(""), ::boost::python::arg("")))
.def("preserveDofName", static_cast<void (dart::dynamics::ZeroDofJoint::*)(std::size_t, bool)>(&dart::dynamics::ZeroDofJoint::preserveDofName), (::boost::python::arg(""), ::boost::python::arg("")))
.def("isDofNamePreserved", static_cast<bool (dart::dynamics::ZeroDofJoint::*)(std::size_t) const>(&dart::dynamics::ZeroDofJoint::isDofNamePreserved), (::boost::python::arg("")))
.def("getDofName", static_cast<const std::string &(dart::dynamics::ZeroDofJoint::*)(std::size_t) const>(&dart::dynamics::ZeroDofJoint::getDofName), ::boost::python::return_value_policy<boost::python::copy_const_reference >(), (::boost::python::arg("")))
.def("getNumDofs", static_cast<std::size_t (dart::dynamics::ZeroDofJoint::*)() const>(&dart::dynamics::ZeroDofJoint::getNumDofs))
.def("getIndexInSkeleton", static_cast<std::size_t (dart::dynamics::ZeroDofJoint::*)(std::size_t) const>(&dart::dynamics::ZeroDofJoint::getIndexInSkeleton), (::boost::python::arg("_index")))
.def("getIndexInTree", static_cast<std::size_t (dart::dynamics::ZeroDofJoint::*)(std::size_t) const>(&dart::dynamics::ZeroDofJoint::getIndexInTree), (::boost::python::arg("_index")))
.def("setCommand", static_cast<void (dart::dynamics::ZeroDofJoint::*)(std::size_t, double)>(&dart::dynamics::ZeroDofJoint::setCommand), (::boost::python::arg("_index"), ::boost::python::arg("_command")))
.def("getCommand", static_cast<double (dart::dynamics::ZeroDofJoint::*)(std::size_t) const>(&dart::dynamics::ZeroDofJoint::getCommand), (::boost::python::arg("_index")))
.def("setCommands", static_cast<void (dart::dynamics::ZeroDofJoint::*)(const Eigen::VectorXd &)>(&dart::dynamics::ZeroDofJoint::setCommands), (::boost::python::arg("_commands")))
.def("getCommands", static_cast<Eigen::VectorXd (dart::dynamics::ZeroDofJoint::*)() const>(&dart::dynamics::ZeroDofJoint::getCommands))
.def("resetCommands", static_cast<void (dart::dynamics::ZeroDofJoint::*)()>(&dart::dynamics::ZeroDofJoint::resetCommands))
.def("setPosition", static_cast<void (dart::dynamics::ZeroDofJoint::*)(std::size_t, double)>(&dart::dynamics::ZeroDofJoint::setPosition), (::boost::python::arg(""), ::boost::python::arg("")))
.def("getPosition", static_cast<double (dart::dynamics::ZeroDofJoint::*)(std::size_t) const>(&dart::dynamics::ZeroDofJoint::getPosition), (::boost::python::arg("_index")))
.def("setPositions", static_cast<void (dart::dynamics::ZeroDofJoint::*)(const Eigen::VectorXd &)>(&dart::dynamics::ZeroDofJoint::setPositions), (::boost::python::arg("_positions")))
.def("getPositions", static_cast<Eigen::VectorXd (dart::dynamics::ZeroDofJoint::*)() const>(&dart::dynamics::ZeroDofJoint::getPositions))
.def("setPositionLowerLimit", static_cast<void (dart::dynamics::ZeroDofJoint::*)(std::size_t, double)>(&dart::dynamics::ZeroDofJoint::setPositionLowerLimit), (::boost::python::arg("_index"), ::boost::python::arg("_position")))
.def("getPositionLowerLimit", static_cast<double (dart::dynamics::ZeroDofJoint::*)(std::size_t) const>(&dart::dynamics::ZeroDofJoint::getPositionLowerLimit), (::boost::python::arg("_index")))
.def("setPositionUpperLimit", static_cast<void (dart::dynamics::ZeroDofJoint::*)(std::size_t, double)>(&dart::dynamics::ZeroDofJoint::setPositionUpperLimit), (::boost::python::arg("_index"), ::boost::python::arg("_position")))
.def("getPositionUpperLimit", static_cast<double (dart::dynamics::ZeroDofJoint::*)(std::size_t) const>(&dart::dynamics::ZeroDofJoint::getPositionUpperLimit), (::boost::python::arg("_index")))
.def("hasPositionLimit", static_cast<bool (dart::dynamics::ZeroDofJoint::*)(std::size_t) const>(&dart::dynamics::ZeroDofJoint::hasPositionLimit), (::boost::python::arg("_index")))
.def("resetPosition", static_cast<void (dart::dynamics::ZeroDofJoint::*)(std::size_t)>(&dart::dynamics::ZeroDofJoint::resetPosition), (::boost::python::arg("_index")))
.def("resetPositions", static_cast<void (dart::dynamics::ZeroDofJoint::*)()>(&dart::dynamics::ZeroDofJoint::resetPositions))
.def("setInitialPosition", static_cast<void (dart::dynamics::ZeroDofJoint::*)(std::size_t, double)>(&dart::dynamics::ZeroDofJoint::setInitialPosition), (::boost::python::arg("_index"), ::boost::python::arg("_initial")))
.def("getInitialPosition", static_cast<double (dart::dynamics::ZeroDofJoint::*)(std::size_t) const>(&dart::dynamics::ZeroDofJoint::getInitialPosition), (::boost::python::arg("_index")))
.def("setInitialPositions", static_cast<void (dart::dynamics::ZeroDofJoint::*)(const Eigen::VectorXd &)>(&dart::dynamics::ZeroDofJoint::setInitialPositions), (::boost::python::arg("_initial")))
.def("getInitialPositions", static_cast<Eigen::VectorXd (dart::dynamics::ZeroDofJoint::*)() const>(&dart::dynamics::ZeroDofJoint::getInitialPositions))
.def("setVelocity", static_cast<void (dart::dynamics::ZeroDofJoint::*)(std::size_t, double)>(&dart::dynamics::ZeroDofJoint::setVelocity), (::boost::python::arg("_index"), ::boost::python::arg("_velocity")))
.def("getVelocity", static_cast<double (dart::dynamics::ZeroDofJoint::*)(std::size_t) const>(&dart::dynamics::ZeroDofJoint::getVelocity), (::boost::python::arg("_index")))
.def("setVelocities", static_cast<void (dart::dynamics::ZeroDofJoint::*)(const Eigen::VectorXd &)>(&dart::dynamics::ZeroDofJoint::setVelocities), (::boost::python::arg("_velocities")))
.def("getVelocities", static_cast<Eigen::VectorXd (dart::dynamics::ZeroDofJoint::*)() const>(&dart::dynamics::ZeroDofJoint::getVelocities))
.def("setVelocityLowerLimit", static_cast<void (dart::dynamics::ZeroDofJoint::*)(std::size_t, double)>(&dart::dynamics::ZeroDofJoint::setVelocityLowerLimit), (::boost::python::arg("_index"), ::boost::python::arg("_velocity")))
.def("getVelocityLowerLimit", static_cast<double (dart::dynamics::ZeroDofJoint::*)(std::size_t) const>(&dart::dynamics::ZeroDofJoint::getVelocityLowerLimit), (::boost::python::arg("_index")))
.def("setVelocityUpperLimit", static_cast<void (dart::dynamics::ZeroDofJoint::*)(std::size_t, double)>(&dart::dynamics::ZeroDofJoint::setVelocityUpperLimit), (::boost::python::arg("_index"), ::boost::python::arg("_velocity")))
.def("getVelocityUpperLimit", static_cast<double (dart::dynamics::ZeroDofJoint::*)(std::size_t) const>(&dart::dynamics::ZeroDofJoint::getVelocityUpperLimit), (::boost::python::arg("_index")))
.def("resetVelocity", static_cast<void (dart::dynamics::ZeroDofJoint::*)(std::size_t)>(&dart::dynamics::ZeroDofJoint::resetVelocity), (::boost::python::arg("_index")))
.def("resetVelocities", static_cast<void (dart::dynamics::ZeroDofJoint::*)()>(&dart::dynamics::ZeroDofJoint::resetVelocities))
.def("setInitialVelocity", static_cast<void (dart::dynamics::ZeroDofJoint::*)(std::size_t, double)>(&dart::dynamics::ZeroDofJoint::setInitialVelocity), (::boost::python::arg("_index"), ::boost::python::arg("_initial")))
.def("getInitialVelocity", static_cast<double (dart::dynamics::ZeroDofJoint::*)(std::size_t) const>(&dart::dynamics::ZeroDofJoint::getInitialVelocity), (::boost::python::arg("_index")))
.def("setInitialVelocities", static_cast<void (dart::dynamics::ZeroDofJoint::*)(const Eigen::VectorXd &)>(&dart::dynamics::ZeroDofJoint::setInitialVelocities), (::boost::python::arg("_initial")))
.def("getInitialVelocities", static_cast<Eigen::VectorXd (dart::dynamics::ZeroDofJoint::*)() const>(&dart::dynamics::ZeroDofJoint::getInitialVelocities))
.def("setAcceleration", static_cast<void (dart::dynamics::ZeroDofJoint::*)(std::size_t, double)>(&dart::dynamics::ZeroDofJoint::setAcceleration), (::boost::python::arg("_index"), ::boost::python::arg("_acceleration")))
.def("getAcceleration", static_cast<double (dart::dynamics::ZeroDofJoint::*)(std::size_t) const>(&dart::dynamics::ZeroDofJoint::getAcceleration), (::boost::python::arg("_index")))
.def("setAccelerations", static_cast<void (dart::dynamics::ZeroDofJoint::*)(const Eigen::VectorXd &)>(&dart::dynamics::ZeroDofJoint::setAccelerations), (::boost::python::arg("_accelerations")))
.def("getAccelerations", static_cast<Eigen::VectorXd (dart::dynamics::ZeroDofJoint::*)() const>(&dart::dynamics::ZeroDofJoint::getAccelerations))
.def("resetAccelerations", static_cast<void (dart::dynamics::ZeroDofJoint::*)()>(&dart::dynamics::ZeroDofJoint::resetAccelerations))
.def("setAccelerationLowerLimit", static_cast<void (dart::dynamics::ZeroDofJoint::*)(std::size_t, double)>(&dart::dynamics::ZeroDofJoint::setAccelerationLowerLimit), (::boost::python::arg("_index"), ::boost::python::arg("_acceleration")))
.def("getAccelerationLowerLimit", static_cast<double (dart::dynamics::ZeroDofJoint::*)(std::size_t) const>(&dart::dynamics::ZeroDofJoint::getAccelerationLowerLimit), (::boost::python::arg("_index")))
.def("setAccelerationUpperLimit", static_cast<void (dart::dynamics::ZeroDofJoint::*)(std::size_t, double)>(&dart::dynamics::ZeroDofJoint::setAccelerationUpperLimit), (::boost::python::arg("_index"), ::boost::python::arg("_acceleration")))
.def("getAccelerationUpperLimit", static_cast<double (dart::dynamics::ZeroDofJoint::*)(std::size_t) const>(&dart::dynamics::ZeroDofJoint::getAccelerationUpperLimit), (::boost::python::arg("_index")))
.def("setForce", static_cast<void (dart::dynamics::ZeroDofJoint::*)(std::size_t, double)>(&dart::dynamics::ZeroDofJoint::setForce), (::boost::python::arg("_index"), ::boost::python::arg("_force")))
.def("getForce", static_cast<double (dart::dynamics::ZeroDofJoint::*)(std::size_t)>(&dart::dynamics::ZeroDofJoint::getForce), (::boost::python::arg("_index")))
.def("setForces", static_cast<void (dart::dynamics::ZeroDofJoint::*)(const Eigen::VectorXd &)>(&dart::dynamics::ZeroDofJoint::setForces), (::boost::python::arg("_forces")))
.def("getForces", static_cast<Eigen::VectorXd (dart::dynamics::ZeroDofJoint::*)() const>(&dart::dynamics::ZeroDofJoint::getForces))
.def("resetForces", static_cast<void (dart::dynamics::ZeroDofJoint::*)()>(&dart::dynamics::ZeroDofJoint::resetForces))
.def("setForceLowerLimit", static_cast<void (dart::dynamics::ZeroDofJoint::*)(std::size_t, double)>(&dart::dynamics::ZeroDofJoint::setForceLowerLimit), (::boost::python::arg("_index"), ::boost::python::arg("_force")))
.def("getForceLowerLimit", static_cast<double (dart::dynamics::ZeroDofJoint::*)(std::size_t) const>(&dart::dynamics::ZeroDofJoint::getForceLowerLimit), (::boost::python::arg("_index")))
.def("setForceUpperLimit", static_cast<void (dart::dynamics::ZeroDofJoint::*)(std::size_t, double)>(&dart::dynamics::ZeroDofJoint::setForceUpperLimit), (::boost::python::arg("_index"), ::boost::python::arg("_force")))
.def("getForceUpperLimit", static_cast<double (dart::dynamics::ZeroDofJoint::*)(std::size_t) const>(&dart::dynamics::ZeroDofJoint::getForceUpperLimit), (::boost::python::arg("_index")))
.def("setVelocityChange", static_cast<void (dart::dynamics::ZeroDofJoint::*)(std::size_t, double)>(&dart::dynamics::ZeroDofJoint::setVelocityChange), (::boost::python::arg("_index"), ::boost::python::arg("_velocityChange")))
.def("getVelocityChange", static_cast<double (dart::dynamics::ZeroDofJoint::*)(std::size_t) const>(&dart::dynamics::ZeroDofJoint::getVelocityChange), (::boost::python::arg("_index")))
.def("resetVelocityChanges", static_cast<void (dart::dynamics::ZeroDofJoint::*)()>(&dart::dynamics::ZeroDofJoint::resetVelocityChanges))
.def("setConstraintImpulse", static_cast<void (dart::dynamics::ZeroDofJoint::*)(std::size_t, double)>(&dart::dynamics::ZeroDofJoint::setConstraintImpulse), (::boost::python::arg("_index"), ::boost::python::arg("_impulse")))
.def("getConstraintImpulse", static_cast<double (dart::dynamics::ZeroDofJoint::*)(std::size_t) const>(&dart::dynamics::ZeroDofJoint::getConstraintImpulse), (::boost::python::arg("_index")))
.def("resetConstraintImpulses", static_cast<void (dart::dynamics::ZeroDofJoint::*)()>(&dart::dynamics::ZeroDofJoint::resetConstraintImpulses))
.def("integratePositions", static_cast<void (dart::dynamics::ZeroDofJoint::*)(double)>(&dart::dynamics::ZeroDofJoint::integratePositions), (::boost::python::arg("_dt")))
.def("integrateVelocities", static_cast<void (dart::dynamics::ZeroDofJoint::*)(double)>(&dart::dynamics::ZeroDofJoint::integrateVelocities), (::boost::python::arg("_dt")))
.def("getPositionDifferences", static_cast<Eigen::VectorXd (dart::dynamics::ZeroDofJoint::*)(const Eigen::VectorXd &, const Eigen::VectorXd &) const>(&dart::dynamics::ZeroDofJoint::getPositionDifferences), (::boost::python::arg("_q2"), ::boost::python::arg("_q1")))
.def("setSpringStiffness", static_cast<void (dart::dynamics::ZeroDofJoint::*)(std::size_t, double)>(&dart::dynamics::ZeroDofJoint::setSpringStiffness), (::boost::python::arg("_index"), ::boost::python::arg("_k")))
.def("getSpringStiffness", static_cast<double (dart::dynamics::ZeroDofJoint::*)(std::size_t) const>(&dart::dynamics::ZeroDofJoint::getSpringStiffness), (::boost::python::arg("_index")))
.def("setRestPosition", static_cast<void (dart::dynamics::ZeroDofJoint::*)(std::size_t, double)>(&dart::dynamics::ZeroDofJoint::setRestPosition), (::boost::python::arg("_index"), ::boost::python::arg("_q0")))
.def("getRestPosition", static_cast<double (dart::dynamics::ZeroDofJoint::*)(std::size_t) const>(&dart::dynamics::ZeroDofJoint::getRestPosition), (::boost::python::arg("_index")))
.def("setDampingCoefficient", static_cast<void (dart::dynamics::ZeroDofJoint::*)(std::size_t, double)>(&dart::dynamics::ZeroDofJoint::setDampingCoefficient), (::boost::python::arg("_index"), ::boost::python::arg("_d")))
.def("getDampingCoefficient", static_cast<double (dart::dynamics::ZeroDofJoint::*)(std::size_t) const>(&dart::dynamics::ZeroDofJoint::getDampingCoefficient), (::boost::python::arg("_index")))
.def("setCoulombFriction", static_cast<void (dart::dynamics::ZeroDofJoint::*)(std::size_t, double)>(&dart::dynamics::ZeroDofJoint::setCoulombFriction), (::boost::python::arg("_index"), ::boost::python::arg("_friction")))
.def("getCoulombFriction", static_cast<double (dart::dynamics::ZeroDofJoint::*)(std::size_t) const>(&dart::dynamics::ZeroDofJoint::getCoulombFriction), (::boost::python::arg("_index")))
.def("getPotentialEnergy", static_cast<double (dart::dynamics::ZeroDofJoint::*)() const>(&dart::dynamics::ZeroDofJoint::getPotentialEnergy))
.def("getBodyConstraintWrench", static_cast<Eigen::Vector6d (dart::dynamics::ZeroDofJoint::*)() const>(&dart::dynamics::ZeroDofJoint::getBodyConstraintWrench))
;
}

/* footer */
