#include </homes/mkoval/dart-ws/src/dartpy/src/pointers.h>

#include <boost/python.hpp>
#include <cmath>
#include </home/mkoval/storage/dartpy-ws/src/dartpy/src/placeholder.cpp>

/* postinclude */

void _ZN4dart8dynamics12MetaSkeletonE()
{
::boost::python::class_<dart::dynamics::MetaSkeleton, ::boost::noncopyable, dart::dynamics::MetaSkeleton *, ::boost::python::bases<dart::common::Subject > >("MetaSkeleton", boost::python::no_init)
.def("setName", static_cast<const std::string &(dart::dynamics::MetaSkeleton::*)(const std::string &)>(&dart::dynamics::MetaSkeleton::setName), ::boost::python::return_value_policy<boost::python::copy_const_reference >(), (::boost::python::arg("_name")))
.def("getName", static_cast<const std::string &(dart::dynamics::MetaSkeleton::*)() const>(&dart::dynamics::MetaSkeleton::getName), ::boost::python::return_value_policy<boost::python::copy_const_reference >())
.def("getNumBodyNodes", static_cast<std::size_t (dart::dynamics::MetaSkeleton::*)() const>(&dart::dynamics::MetaSkeleton::getNumBodyNodes))
.def("getBodyNode", static_cast<dart::dynamics::BodyNode *(dart::dynamics::MetaSkeleton::*)(std::size_t)>(&dart::dynamics::MetaSkeleton::getBodyNode), ::boost::python::return_value_policy<boost::python::return_by_smart_ptr<dart::dynamics::BodyNodePtr> >(), (::boost::python::arg("_idx")))
.def("getIndexOf", static_cast<std::size_t (dart::dynamics::MetaSkeleton::*)(const dart::dynamics::BodyNode *, bool) const>(&dart::dynamics::MetaSkeleton::getIndexOf), (::boost::python::arg("_bn"), ::boost::python::arg("_warning") = true))
.def("getNumJoints", static_cast<std::size_t (dart::dynamics::MetaSkeleton::*)() const>(&dart::dynamics::MetaSkeleton::getNumJoints))
.def("getJoint", static_cast<dart::dynamics::Joint *(dart::dynamics::MetaSkeleton::*)(std::size_t)>(&dart::dynamics::MetaSkeleton::getJoint), ::boost::python::return_value_policy<boost::python::return_by_smart_ptr<dart::dynamics::JointPtr> >(), (::boost::python::arg("_idx")))
.def("getIndexOf", static_cast<std::size_t (dart::dynamics::MetaSkeleton::*)(const dart::dynamics::Joint *, bool) const>(&dart::dynamics::MetaSkeleton::getIndexOf), (::boost::python::arg("_joint"), ::boost::python::arg("_warning") = true))
.def("getNumDofs", static_cast<std::size_t (dart::dynamics::MetaSkeleton::*)() const>(&dart::dynamics::MetaSkeleton::getNumDofs))
.def("getDof", static_cast<dart::dynamics::DegreeOfFreedom *(dart::dynamics::MetaSkeleton::*)(std::size_t)>(&dart::dynamics::MetaSkeleton::getDof), ::boost::python::return_value_policy<boost::python::return_by_smart_ptr<dart::dynamics::DegreeOfFreedomPtr> >(), (::boost::python::arg("_idx")))
.def("getDofs", static_cast<const std::vector<dart::dynamics::DegreeOfFreedom *> &(dart::dynamics::MetaSkeleton::*)()>(&dart::dynamics::MetaSkeleton::getDofs), ::boost::python::return_value_policy<boost::python::copy_const_reference >())
.def("getIndexOf", static_cast<std::size_t (dart::dynamics::MetaSkeleton::*)(const dart::dynamics::DegreeOfFreedom *, bool) const>(&dart::dynamics::MetaSkeleton::getIndexOf), (::boost::python::arg("_dof"), ::boost::python::arg("_warning") = true))
.def("setCommand", static_cast<void (dart::dynamics::MetaSkeleton::*)(std::size_t, double)>(&dart::dynamics::MetaSkeleton::setCommand), (::boost::python::arg("_index"), ::boost::python::arg("_command")))
.def("getCommand", static_cast<double (dart::dynamics::MetaSkeleton::*)(std::size_t) const>(&dart::dynamics::MetaSkeleton::getCommand), (::boost::python::arg("_index")))
.def("setCommands", static_cast<void (dart::dynamics::MetaSkeleton::*)(const Eigen::VectorXd &)>(&dart::dynamics::MetaSkeleton::setCommands), (::boost::python::arg("_commands")))
.def("setCommands", static_cast<void (dart::dynamics::MetaSkeleton::*)(const std::vector<std::size_t> &, const Eigen::VectorXd &)>(&dart::dynamics::MetaSkeleton::setCommands), (::boost::python::arg("_indices"), ::boost::python::arg("_commands")))
.def("getCommands", static_cast<Eigen::VectorXd (dart::dynamics::MetaSkeleton::*)() const>(&dart::dynamics::MetaSkeleton::getCommands))
.def("getCommands", static_cast<Eigen::VectorXd (dart::dynamics::MetaSkeleton::*)(const std::vector<std::size_t> &) const>(&dart::dynamics::MetaSkeleton::getCommands), (::boost::python::arg("_indices")))
.def("resetCommands", static_cast<void (dart::dynamics::MetaSkeleton::*)()>(&dart::dynamics::MetaSkeleton::resetCommands))
.def("setPosition", static_cast<void (dart::dynamics::MetaSkeleton::*)(std::size_t, double)>(&dart::dynamics::MetaSkeleton::setPosition), (::boost::python::arg("index"), ::boost::python::arg("_position")))
.def("getPosition", static_cast<double (dart::dynamics::MetaSkeleton::*)(std::size_t) const>(&dart::dynamics::MetaSkeleton::getPosition), (::boost::python::arg("_index")))
.def("setPositions", static_cast<void (dart::dynamics::MetaSkeleton::*)(const Eigen::VectorXd &)>(&dart::dynamics::MetaSkeleton::setPositions), (::boost::python::arg("_positions")))
.def("setPositions", static_cast<void (dart::dynamics::MetaSkeleton::*)(const std::vector<std::size_t> &, const Eigen::VectorXd &)>(&dart::dynamics::MetaSkeleton::setPositions), (::boost::python::arg("_indices"), ::boost::python::arg("_positions")))
.def("getPositions", static_cast<Eigen::VectorXd (dart::dynamics::MetaSkeleton::*)() const>(&dart::dynamics::MetaSkeleton::getPositions))
.def("getPositions", static_cast<Eigen::VectorXd (dart::dynamics::MetaSkeleton::*)(const std::vector<std::size_t> &) const>(&dart::dynamics::MetaSkeleton::getPositions), (::boost::python::arg("_indices")))
.def("resetPositions", static_cast<void (dart::dynamics::MetaSkeleton::*)()>(&dart::dynamics::MetaSkeleton::resetPositions))
.def("setPositionLowerLimit", static_cast<void (dart::dynamics::MetaSkeleton::*)(std::size_t, double)>(&dart::dynamics::MetaSkeleton::setPositionLowerLimit), (::boost::python::arg("_index"), ::boost::python::arg("_position")))
.def("getPositionLowerLimit", static_cast<double (dart::dynamics::MetaSkeleton::*)(std::size_t) const>(&dart::dynamics::MetaSkeleton::getPositionLowerLimit), (::boost::python::arg("_index")))
.def("setPositionUpperLimit", static_cast<void (dart::dynamics::MetaSkeleton::*)(std::size_t, double)>(&dart::dynamics::MetaSkeleton::setPositionUpperLimit), (::boost::python::arg("_index"), ::boost::python::arg("_position")))
.def("getPositionUpperLimit", static_cast<double (dart::dynamics::MetaSkeleton::*)(std::size_t) const>(&dart::dynamics::MetaSkeleton::getPositionUpperLimit), (::boost::python::arg("_index")))
.def("setVelocity", static_cast<void (dart::dynamics::MetaSkeleton::*)(std::size_t, double)>(&dart::dynamics::MetaSkeleton::setVelocity), (::boost::python::arg("_index"), ::boost::python::arg("_velocity")))
.def("getVelocity", static_cast<double (dart::dynamics::MetaSkeleton::*)(std::size_t) const>(&dart::dynamics::MetaSkeleton::getVelocity), (::boost::python::arg("_index")))
.def("setVelocities", static_cast<void (dart::dynamics::MetaSkeleton::*)(const Eigen::VectorXd &)>(&dart::dynamics::MetaSkeleton::setVelocities), (::boost::python::arg("_velocities")))
.def("setVelocities", static_cast<void (dart::dynamics::MetaSkeleton::*)(const std::vector<std::size_t> &, const Eigen::VectorXd &)>(&dart::dynamics::MetaSkeleton::setVelocities), (::boost::python::arg("_indices"), ::boost::python::arg("_velocities")))
.def("getVelocities", static_cast<Eigen::VectorXd (dart::dynamics::MetaSkeleton::*)() const>(&dart::dynamics::MetaSkeleton::getVelocities))
.def("getVelocities", static_cast<Eigen::VectorXd (dart::dynamics::MetaSkeleton::*)(const std::vector<std::size_t> &) const>(&dart::dynamics::MetaSkeleton::getVelocities), (::boost::python::arg("_indices")))
.def("resetVelocities", static_cast<void (dart::dynamics::MetaSkeleton::*)()>(&dart::dynamics::MetaSkeleton::resetVelocities))
.def("setVelocityLowerLimit", static_cast<void (dart::dynamics::MetaSkeleton::*)(std::size_t, double)>(&dart::dynamics::MetaSkeleton::setVelocityLowerLimit), (::boost::python::arg("_index"), ::boost::python::arg("_velocity")))
.def("getVelocityLowerLimit", static_cast<double (dart::dynamics::MetaSkeleton::*)(std::size_t)>(&dart::dynamics::MetaSkeleton::getVelocityLowerLimit), (::boost::python::arg("_index")))
.def("setVelocityUpperLimit", static_cast<void (dart::dynamics::MetaSkeleton::*)(std::size_t, double)>(&dart::dynamics::MetaSkeleton::setVelocityUpperLimit), (::boost::python::arg("_index"), ::boost::python::arg("_velocity")))
.def("getVelocityUpperLimit", static_cast<double (dart::dynamics::MetaSkeleton::*)(std::size_t)>(&dart::dynamics::MetaSkeleton::getVelocityUpperLimit), (::boost::python::arg("_index")))
.def("setAcceleration", static_cast<void (dart::dynamics::MetaSkeleton::*)(std::size_t, double)>(&dart::dynamics::MetaSkeleton::setAcceleration), (::boost::python::arg("_index"), ::boost::python::arg("_acceleration")))
.def("getAcceleration", static_cast<double (dart::dynamics::MetaSkeleton::*)(std::size_t) const>(&dart::dynamics::MetaSkeleton::getAcceleration), (::boost::python::arg("_index")))
.def("setAccelerations", static_cast<void (dart::dynamics::MetaSkeleton::*)(const Eigen::VectorXd &)>(&dart::dynamics::MetaSkeleton::setAccelerations), (::boost::python::arg("_accelerations")))
.def("setAccelerations", static_cast<void (dart::dynamics::MetaSkeleton::*)(const std::vector<std::size_t> &, const Eigen::VectorXd &)>(&dart::dynamics::MetaSkeleton::setAccelerations), (::boost::python::arg("_indices"), ::boost::python::arg("_accelerations")))
.def("getAccelerations", static_cast<Eigen::VectorXd (dart::dynamics::MetaSkeleton::*)() const>(&dart::dynamics::MetaSkeleton::getAccelerations))
.def("getAccelerations", static_cast<Eigen::VectorXd (dart::dynamics::MetaSkeleton::*)(const std::vector<std::size_t> &) const>(&dart::dynamics::MetaSkeleton::getAccelerations), (::boost::python::arg("_indices")))
.def("resetAccelerations", static_cast<void (dart::dynamics::MetaSkeleton::*)()>(&dart::dynamics::MetaSkeleton::resetAccelerations))
.def("setAccelerationLowerLimit", static_cast<void (dart::dynamics::MetaSkeleton::*)(std::size_t, double)>(&dart::dynamics::MetaSkeleton::setAccelerationLowerLimit), (::boost::python::arg("_index"), ::boost::python::arg("_acceleration")))
.def("getAccelerationLowerLimit", static_cast<double (dart::dynamics::MetaSkeleton::*)(std::size_t) const>(&dart::dynamics::MetaSkeleton::getAccelerationLowerLimit), (::boost::python::arg("_index")))
.def("setAccelerationUpperLimit", static_cast<void (dart::dynamics::MetaSkeleton::*)(std::size_t, double)>(&dart::dynamics::MetaSkeleton::setAccelerationUpperLimit), (::boost::python::arg("_index"), ::boost::python::arg("_acceleration")))
.def("getAccelerationUpperLimit", static_cast<double (dart::dynamics::MetaSkeleton::*)(std::size_t) const>(&dart::dynamics::MetaSkeleton::getAccelerationUpperLimit), (::boost::python::arg("_index")))
.def("setForce", static_cast<void (dart::dynamics::MetaSkeleton::*)(std::size_t, double)>(&dart::dynamics::MetaSkeleton::setForce), (::boost::python::arg("_index"), ::boost::python::arg("_force")))
.def("getForce", static_cast<double (dart::dynamics::MetaSkeleton::*)(std::size_t) const>(&dart::dynamics::MetaSkeleton::getForce), (::boost::python::arg("_index")))
.def("setForces", static_cast<void (dart::dynamics::MetaSkeleton::*)(const Eigen::VectorXd &)>(&dart::dynamics::MetaSkeleton::setForces), (::boost::python::arg("_forces")))
.def("setForces", static_cast<void (dart::dynamics::MetaSkeleton::*)(const std::vector<std::size_t> &, const Eigen::VectorXd &)>(&dart::dynamics::MetaSkeleton::setForces), (::boost::python::arg("_index"), ::boost::python::arg("_forces")))
.def("getForces", static_cast<Eigen::VectorXd (dart::dynamics::MetaSkeleton::*)() const>(&dart::dynamics::MetaSkeleton::getForces))
.def("getForces", static_cast<Eigen::VectorXd (dart::dynamics::MetaSkeleton::*)(const std::vector<std::size_t> &) const>(&dart::dynamics::MetaSkeleton::getForces), (::boost::python::arg("_indices")))
.def("resetGeneralizedForces", static_cast<void (dart::dynamics::MetaSkeleton::*)()>(&dart::dynamics::MetaSkeleton::resetGeneralizedForces))
.def("setForceLowerLimit", static_cast<void (dart::dynamics::MetaSkeleton::*)(std::size_t, double)>(&dart::dynamics::MetaSkeleton::setForceLowerLimit), (::boost::python::arg("_index"), ::boost::python::arg("_force")))
.def("getForceLowerLimit", static_cast<double (dart::dynamics::MetaSkeleton::*)(std::size_t) const>(&dart::dynamics::MetaSkeleton::getForceLowerLimit), (::boost::python::arg("_index")))
.def("setForceUpperLimit", static_cast<void (dart::dynamics::MetaSkeleton::*)(std::size_t, double)>(&dart::dynamics::MetaSkeleton::setForceUpperLimit), (::boost::python::arg("_index"), ::boost::python::arg("_force")))
.def("getForceUpperLimit", static_cast<double (dart::dynamics::MetaSkeleton::*)(std::size_t) const>(&dart::dynamics::MetaSkeleton::getForceUpperLimit), (::boost::python::arg("_index")))
.def("getVelocityChanges", static_cast<Eigen::VectorXd (dart::dynamics::MetaSkeleton::*)() const>(&dart::dynamics::MetaSkeleton::getVelocityChanges))
.def("setJointConstraintImpulses", static_cast<void (dart::dynamics::MetaSkeleton::*)(const Eigen::VectorXd &)>(&dart::dynamics::MetaSkeleton::setJointConstraintImpulses), (::boost::python::arg("_impulses")))
.def("getJointConstraintImpulses", static_cast<Eigen::VectorXd (dart::dynamics::MetaSkeleton::*)() const>(&dart::dynamics::MetaSkeleton::getJointConstraintImpulses))
.def("getJacobian", static_cast<dart::math::Jacobian (dart::dynamics::MetaSkeleton::*)(const dart::dynamics::JacobianNode *) const>(&dart::dynamics::MetaSkeleton::getJacobian), (::boost::python::arg("_node")))
.def("getJacobian", static_cast<dart::math::Jacobian (dart::dynamics::MetaSkeleton::*)(const dart::dynamics::JacobianNode *, const dart::dynamics::Frame *) const>(&dart::dynamics::MetaSkeleton::getJacobian), (::boost::python::arg("_node"), ::boost::python::arg("_inCoordinatesOf")))
.def("getJacobian", static_cast<dart::math::Jacobian (dart::dynamics::MetaSkeleton::*)(const dart::dynamics::JacobianNode *, const Eigen::Vector3d &) const>(&dart::dynamics::MetaSkeleton::getJacobian), (::boost::python::arg("_node"), ::boost::python::arg("_localOffset")))
.def("getJacobian", static_cast<dart::math::Jacobian (dart::dynamics::MetaSkeleton::*)(const dart::dynamics::JacobianNode *, const Eigen::Vector3d &, const dart::dynamics::Frame *) const>(&dart::dynamics::MetaSkeleton::getJacobian), (::boost::python::arg("_node"), ::boost::python::arg("_localOffset"), ::boost::python::arg("_inCoordinatesOf")))
.def("getWorldJacobian", static_cast<dart::math::Jacobian (dart::dynamics::MetaSkeleton::*)(const dart::dynamics::JacobianNode *) const>(&dart::dynamics::MetaSkeleton::getWorldJacobian), (::boost::python::arg("_node")))
.def("getWorldJacobian", static_cast<dart::math::Jacobian (dart::dynamics::MetaSkeleton::*)(const dart::dynamics::JacobianNode *, const Eigen::Vector3d &) const>(&dart::dynamics::MetaSkeleton::getWorldJacobian), (::boost::python::arg("_node"), ::boost::python::arg("_localOffset")))
.def("getLinearJacobian", static_cast<dart::math::LinearJacobian (dart::dynamics::MetaSkeleton::*)(const dart::dynamics::JacobianNode *, const dart::dynamics::Frame *) const>(&dart::dynamics::MetaSkeleton::getLinearJacobian), (::boost::python::arg("_node"), ::boost::python::arg("_inCoordinatesOf")))
.def("getLinearJacobian", static_cast<dart::math::LinearJacobian (dart::dynamics::MetaSkeleton::*)(const dart::dynamics::JacobianNode *, const Eigen::Vector3d &, const dart::dynamics::Frame *) const>(&dart::dynamics::MetaSkeleton::getLinearJacobian), (::boost::python::arg("_node"), ::boost::python::arg("_localOffset"), ::boost::python::arg("_inCoordinatesOf")))
.def("getAngularJacobian", static_cast<dart::math::AngularJacobian (dart::dynamics::MetaSkeleton::*)(const dart::dynamics::JacobianNode *, const dart::dynamics::Frame *) const>(&dart::dynamics::MetaSkeleton::getAngularJacobian), (::boost::python::arg("_node"), ::boost::python::arg("_inCoordinatesOf")))
.def("getJacobianSpatialDeriv", static_cast<dart::math::Jacobian (dart::dynamics::MetaSkeleton::*)(const dart::dynamics::JacobianNode *) const>(&dart::dynamics::MetaSkeleton::getJacobianSpatialDeriv), (::boost::python::arg("_node")))
.def("getJacobianSpatialDeriv", static_cast<dart::math::Jacobian (dart::dynamics::MetaSkeleton::*)(const dart::dynamics::JacobianNode *, const dart::dynamics::Frame *) const>(&dart::dynamics::MetaSkeleton::getJacobianSpatialDeriv), (::boost::python::arg("_node"), ::boost::python::arg("_inCoordinatesOf")))
.def("getJacobianSpatialDeriv", static_cast<dart::math::Jacobian (dart::dynamics::MetaSkeleton::*)(const dart::dynamics::JacobianNode *, const Eigen::Vector3d &) const>(&dart::dynamics::MetaSkeleton::getJacobianSpatialDeriv), (::boost::python::arg("_node"), ::boost::python::arg("_localOffset")))
.def("getJacobianSpatialDeriv", static_cast<dart::math::Jacobian (dart::dynamics::MetaSkeleton::*)(const dart::dynamics::JacobianNode *, const Eigen::Vector3d &, const dart::dynamics::Frame *) const>(&dart::dynamics::MetaSkeleton::getJacobianSpatialDeriv), (::boost::python::arg("_node"), ::boost::python::arg("_localOffset"), ::boost::python::arg("_inCoordinatesOf")))
.def("getJacobianClassicDeriv", static_cast<dart::math::Jacobian (dart::dynamics::MetaSkeleton::*)(const dart::dynamics::JacobianNode *) const>(&dart::dynamics::MetaSkeleton::getJacobianClassicDeriv), (::boost::python::arg("_node")))
.def("getJacobianClassicDeriv", static_cast<dart::math::Jacobian (dart::dynamics::MetaSkeleton::*)(const dart::dynamics::JacobianNode *, const dart::dynamics::Frame *) const>(&dart::dynamics::MetaSkeleton::getJacobianClassicDeriv), (::boost::python::arg("_node"), ::boost::python::arg("_inCoordinatesOf")))
.def("getJacobianClassicDeriv", static_cast<dart::math::Jacobian (dart::dynamics::MetaSkeleton::*)(const dart::dynamics::JacobianNode *, const Eigen::Vector3d &, const dart::dynamics::Frame *) const>(&dart::dynamics::MetaSkeleton::getJacobianClassicDeriv), (::boost::python::arg("_node"), ::boost::python::arg("_localOffset"), ::boost::python::arg("_inCoordinatesOf")))
.def("getLinearJacobianDeriv", static_cast<dart::math::LinearJacobian (dart::dynamics::MetaSkeleton::*)(const dart::dynamics::JacobianNode *, const dart::dynamics::Frame *) const>(&dart::dynamics::MetaSkeleton::getLinearJacobianDeriv), (::boost::python::arg("_node"), ::boost::python::arg("_inCoordinatesOf")))
.def("getLinearJacobianDeriv", static_cast<dart::math::LinearJacobian (dart::dynamics::MetaSkeleton::*)(const dart::dynamics::JacobianNode *, const Eigen::Vector3d &, const dart::dynamics::Frame *) const>(&dart::dynamics::MetaSkeleton::getLinearJacobianDeriv), (::boost::python::arg("_node"), ::boost::python::arg("_localOffset"), ::boost::python::arg("_inCoordinatesOf")))
.def("getAngularJacobianDeriv", static_cast<dart::math::AngularJacobian (dart::dynamics::MetaSkeleton::*)(const dart::dynamics::JacobianNode *, const dart::dynamics::Frame *) const>(&dart::dynamics::MetaSkeleton::getAngularJacobianDeriv), (::boost::python::arg("_node"), ::boost::python::arg("_inCoordinatesOf")))
.def("getMass", static_cast<double (dart::dynamics::MetaSkeleton::*)() const>(&dart::dynamics::MetaSkeleton::getMass))
.def("getMassMatrix", static_cast<const Eigen::MatrixXd &(dart::dynamics::MetaSkeleton::*)() const>(&dart::dynamics::MetaSkeleton::getMassMatrix), ::boost::python::return_value_policy<boost::python::copy_const_reference >())
.def("getAugMassMatrix", static_cast<const Eigen::MatrixXd &(dart::dynamics::MetaSkeleton::*)() const>(&dart::dynamics::MetaSkeleton::getAugMassMatrix), ::boost::python::return_value_policy<boost::python::copy_const_reference >())
.def("getInvMassMatrix", static_cast<const Eigen::MatrixXd &(dart::dynamics::MetaSkeleton::*)() const>(&dart::dynamics::MetaSkeleton::getInvMassMatrix), ::boost::python::return_value_policy<boost::python::copy_const_reference >())
.def("getInvAugMassMatrix", static_cast<const Eigen::MatrixXd &(dart::dynamics::MetaSkeleton::*)() const>(&dart::dynamics::MetaSkeleton::getInvAugMassMatrix), ::boost::python::return_value_policy<boost::python::copy_const_reference >())
.def("getCoriolisForces", static_cast<const Eigen::VectorXd &(dart::dynamics::MetaSkeleton::*)() const>(&dart::dynamics::MetaSkeleton::getCoriolisForces), ::boost::python::return_value_policy<boost::python::copy_const_reference >())
.def("getGravityForces", static_cast<const Eigen::VectorXd &(dart::dynamics::MetaSkeleton::*)() const>(&dart::dynamics::MetaSkeleton::getGravityForces), ::boost::python::return_value_policy<boost::python::copy_const_reference >())
.def("getCoriolisAndGravityForces", static_cast<const Eigen::VectorXd &(dart::dynamics::MetaSkeleton::*)() const>(&dart::dynamics::MetaSkeleton::getCoriolisAndGravityForces), ::boost::python::return_value_policy<boost::python::copy_const_reference >())
.def("getExternalForces", static_cast<const Eigen::VectorXd &(dart::dynamics::MetaSkeleton::*)() const>(&dart::dynamics::MetaSkeleton::getExternalForces), ::boost::python::return_value_policy<boost::python::copy_const_reference >())
.def("getConstraintForces", static_cast<const Eigen::VectorXd &(dart::dynamics::MetaSkeleton::*)() const>(&dart::dynamics::MetaSkeleton::getConstraintForces), ::boost::python::return_value_policy<boost::python::copy_const_reference >())
.def("clearExternalForces", static_cast<void (dart::dynamics::MetaSkeleton::*)()>(&dart::dynamics::MetaSkeleton::clearExternalForces))
.def("clearInternalForces", static_cast<void (dart::dynamics::MetaSkeleton::*)()>(&dart::dynamics::MetaSkeleton::clearInternalForces))
.def("getKineticEnergy", static_cast<double (dart::dynamics::MetaSkeleton::*)() const>(&dart::dynamics::MetaSkeleton::getKineticEnergy))
.def("getPotentialEnergy", static_cast<double (dart::dynamics::MetaSkeleton::*)() const>(&dart::dynamics::MetaSkeleton::getPotentialEnergy))
.def("getCOM", static_cast<Eigen::Vector3d (dart::dynamics::MetaSkeleton::*)(const dart::dynamics::Frame *) const>(&dart::dynamics::MetaSkeleton::getCOM), (::boost::python::arg("_withRespectTo")))
.def("getCOMSpatialVelocity", static_cast<Eigen::Vector6d (dart::dynamics::MetaSkeleton::*)(const dart::dynamics::Frame *, const dart::dynamics::Frame *) const>(&dart::dynamics::MetaSkeleton::getCOMSpatialVelocity), (::boost::python::arg("_relativeTo"), ::boost::python::arg("_inCoordinatesOf")))
.def("getCOMLinearVelocity", static_cast<Eigen::Vector3d (dart::dynamics::MetaSkeleton::*)(const dart::dynamics::Frame *, const dart::dynamics::Frame *) const>(&dart::dynamics::MetaSkeleton::getCOMLinearVelocity), (::boost::python::arg("_relativeTo"), ::boost::python::arg("_inCoordinatesOf")))
.def("getCOMSpatialAcceleration", static_cast<Eigen::Vector6d (dart::dynamics::MetaSkeleton::*)(const dart::dynamics::Frame *, const dart::dynamics::Frame *) const>(&dart::dynamics::MetaSkeleton::getCOMSpatialAcceleration), (::boost::python::arg("_relativeTo"), ::boost::python::arg("_inCoordinatesOf")))
.def("getCOMLinearAcceleration", static_cast<Eigen::Vector3d (dart::dynamics::MetaSkeleton::*)(const dart::dynamics::Frame *, const dart::dynamics::Frame *) const>(&dart::dynamics::MetaSkeleton::getCOMLinearAcceleration), (::boost::python::arg("_relativeTo"), ::boost::python::arg("_inCoordinatesOf")))
.def("getCOMJacobian", static_cast<dart::math::Jacobian (dart::dynamics::MetaSkeleton::*)(const dart::dynamics::Frame *) const>(&dart::dynamics::MetaSkeleton::getCOMJacobian), (::boost::python::arg("_inCoordinatesOf")))
.def("getCOMLinearJacobian", static_cast<dart::math::LinearJacobian (dart::dynamics::MetaSkeleton::*)(const dart::dynamics::Frame *) const>(&dart::dynamics::MetaSkeleton::getCOMLinearJacobian), (::boost::python::arg("_inCoordinatesOf")))
.def("getCOMJacobianSpatialDeriv", static_cast<dart::math::Jacobian (dart::dynamics::MetaSkeleton::*)(const dart::dynamics::Frame *) const>(&dart::dynamics::MetaSkeleton::getCOMJacobianSpatialDeriv), (::boost::python::arg("_inCoordinatesOf")))
.def("getCOMLinearJacobianDeriv", static_cast<dart::math::LinearJacobian (dart::dynamics::MetaSkeleton::*)(const dart::dynamics::Frame *) const>(&dart::dynamics::MetaSkeleton::getCOMLinearJacobianDeriv), (::boost::python::arg("_inCoordinatesOf")))
;
}

/* footer */
